### ISSUE TITLE
Self closing script tags with src attribute

### ISSUE THREAD

**Issue by donuk** [gawel/pyquery#103] opened 2015-05-20 10:37 UTC
There is a problem in some (maybe all?) browsers where the following is treated differently even though the xml is equivalent:

```<script src='test.js'></script>```
```<script src='test.js'/>```

The second form is interpreted by browsers as missing an end tag so in the following:

```<script src='test.js'/><script src='test2.js'/>```

test2.js would not be loaded (in chrome at least)

It looks like certain pyquery methods cause the former to be replaced with the latter e.g.:
```
el = PyQuery("<html><head><script src='my-script.js'></script></head></html>")
print el.html()
#outputs u'<head><script src="my-script.js"/></head>'
```
I'm not sure there's a neat way around this but thought it was worth mentioning.

For my purposes I have got round it with the following sub-class (which is less correct but behaves better with browsers):
```
class MyPyQuery(PyQuery):
        def html(self,*args,**kwargs):
                for tag in self.find('script'):
                        tag = PyQuery(tag)
                        if len(tag.text())==0:
                                tag.html("&nbsp;")
                html = PyQuery.html(self,*args,**kwargs)
                return html
```

**Comment by mrnfrancesco** [comment] 2015-06-27 00:29
I think this issue could be marked as duplicate of issue #90 .
You can find a solution in my comment at https://github.com/gawel/pyquery/issues/90#issuecomment-106840446 based on `PyQuery.html()` docstring.

**Closed** 2015-06-30 16:28 UTC
